language: ruby
rvm:
- 2.4.1
sudo: required

services:
  - mysql
  - docker
  - memcached
  - elasticsearch
  - redis-server

addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN
  apt:
    packages:
      - oracle-java8-set-default

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.1.deb
  - sudo dpkg -i --force-confnew elasticsearch-5.1.1.deb
  - sudo service elasticsearch start
  - mysql -e 'CREATE DATABASE lupo_test;'

install:
  - travis_retry bundle install

before_script:
  - npm install
  - memcached -p 11211 &
  - cp .env.travis .env
  - mkdir -p tmp/pids
  - mkdir -p log
  - bundle exec sidekiq -d -e production --config config/sidekiq.yml -L log/sidekiq.log
  - sleep 10
  - bundle exec rake db:setup RAILS_ENV=test
  - npm install -g istanbul codeclimate-test-reporter


script:
  - bundle exec rspec spec
  - bundle exec codeclimate-test-reporter

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";
    export REPO=datacite/lupo;
    docker build -f Dockerfile -t $REPO:$COMMIT .;
    docker push $REPO:$COMMIT;
    fi

notifications:
  slack: datacite:Wt8En0ALoTA6Kjc5EOKNDWxN
  email: false
